CREATE DATABASE IF NOT EXISTS mammo_db;

USE mammo_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100) UNIQUE,
    password VARCHAR(255)
    registered_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE report (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    filename VARCHAR(255),
    filedata LONGBLOB,
    upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ALTER TABLE users
-- ADD COLUMN registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
-- MODIFY password VARCHAR(255);

SELECT * FROM users;
SELECT * FROM report;
